blacklistfiles: ["idmap.go","debug.go","checker.go","loader.go","task.go","*.pb.go","*.seg.go"]
blacklistdirs: ["vendor", ".git"]
#path: "E:\\go\\src\\gitlab.woool.com\\evolution\\gameserver\\"
path: "/Users/cohen/workspace/m3game"
ranknum: 10
